site_name: Anti-ADHD
site_description: 아이젠하워 매트릭스 기반 할 일 관리 프로그램
theme:
  name: material
  language: ko
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

repo_name: octxxiii/Anti-ADHD
repo_url: https://github.com/octxxiii/Anti-ADHD

nav:
  - 홈: index.md
  - 사용 방법: user-guide.md
  - 자주 묻는 질문: faq.md
  - 문제 해결: troubleshooting.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg 