site_name: Anti-ADHD
site_description: 아이젠하워 매트릭스로 ADHD를 이기는 할 일 관리 프로그램
site_author: octxxiii
site_url: https://octxxiii.github.io/Anti-ADHD

repo_name: octxxiii/Anti-ADHD
repo_url: https://github.com/octxxiii/Anti-ADHD

theme:
  name: material
  language: ko
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - navigation.prune
    - toc.follow
    - toc.integrate
  palette:
    scheme: slate
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/octxxiii/Anti-ADHD
    - icon: fontawesome/solid/envelope
      link: mailto:kdyw123@gmail.com

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 홈: index.md
  - 사용 방법: usage.md
  - 자주 묻는 질문: faq.md
  - 문제 해결: troubleshooting.md 