name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name=anti_adhd anti_adhd.py
        
    - name: List dist directory
      run: dir dist
      
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: anti-adhd-windows
        path: dist/anti_adhd.exe
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build macOS app
      run: |
        pyinstaller --onefile --windowed --name=anti_adhd anti_adhd.py
        
    - name: List dist directory
      run: ls -l dist
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: anti-adhd-macos
        path: dist/anti_adhd
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --name=anti_adhd anti_adhd.py
        
    - name: List dist directory
      run: ls -l dist
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: anti-adhd-linux
        path: dist/anti_adhd
        if-no-files-found: error

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
        
    - name: List downloaded artifacts
      run: ls -R artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/anti-adhd-windows/anti_adhd.exe
          artifacts/anti-adhd-macos/anti_adhd
          artifacts/anti-adhd-linux/anti_adhd
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 